### ISSUE TITLE
compilation error with gcc 14

### ISSUE THREAD

**Issue by kyxma** [h2oai/datatable#3499]
- Did you find a bug in datatable, or maybe the bug found you?
 
Compilation error

- How to reproduce the bug?

just compile using g++ 14.1.1

- What was the expected behavior?

compilation

- Your environment?
dt version: 1.2.0a
compiler: g++ 14.1.1
os: Arch Linux kernel 6.9
python: 3.12.4  

- Tag the issue with `[bug]` or `[segfault]` (depending on whether it crashes
  Python or not).

[bug]

- Thank you for contributing, and sorry for the inconvenience.

![image](https://github.com/h2oai/datatable/assets/174472780/ebac7b8b-b74c-450b-8683-a64f05d22f82)
