### ISSUE TITLE
Datatable Fails To Install In venv

### ISSUE THREAD

**Issue by TravisCouture** [h2oai/datatable#2695]
- Did you find a bug in datatable, or maybe the bug found you?
Datatable>0.9.0 fails to install in venv.

```
  Failed building wheel for retrying
  Running setup.py clean for retrying
Failed to build bokeh datatable PyYAML retrying
Installing collected packages: pygments, six, python-dateutil, text-unidecode, Faker, numpy, pytz, pandas, MarkupSafe, Jinja2, PyYAML, pyparsing, packaging, pillow, tornado, typing-extensions, bokeh, certifi, cycler, kiwisolver, matplotlib, retrying, plotly, zipp, importlib-metadata, pyrsistent, attrs, jsonschema, toolz, entrypoints, altair, vega-datasets, urllib3, idna, chardet, requests, websockets, h2o-q, wcwidth, blessed, colorama, typesentry, datatable, toml, tabulate, driverlessai
  Running setup.py install for PyYAML ... done
  Running setup.py install for bokeh ... done
  Running setup.py install for retrying ... done
  Running setup.py install for datatable ... done
Successfully installed Faker-4.14.0 Jinja2-2.11.2 MarkupSafe-1.1.1 PyYAML-5.3.1 altair-4.1.0 attrs-20.2.0 blessed-1.17.10 bokeh-2.2.2 certifi-2020.6.20 chardet-3.0.4 colorama-0.4.4 cycler-0.10.0 datatable-0.10.1 driverlessai-1.9.0.3 entrypoints-0.3 h2o-q-0.6.0 idna-2.10 importlib-metadata-2.0.0 jsonschema-3.2.0 kiwisolver-1.2.0 matplotlib-3.3.2 numpy-1.19.2 packaging-20.4 pandas-1.1.3 pillow-7.2.0 plotly-4.11.0 pygments-2.7.1 pyparsing-2.4.7 pyrsistent-0.17.3 python-dateutil-2.8.1 pytz-2020.1 requests-2.24.0

...

Traceback (most recent call last):
  File "run.py", line 12, in <module>
    import datatable as dt
  File "/home/ubuntu/qd-0.6.0-linux-amd64/venv/lib/python3.6/site-packages/datatable/__init__.py", line 24, in <module>
    from .frame import Frame
  File "/home/ubuntu/qd-0.6.0-linux-amd64/venv/lib/python3.6/site-packages/datatable/frame.py", line 23, in <module>
    from datatable.lib._datatable import Frame
  File "/home/ubuntu/qd-0.6.0-linux-amd64/venv/lib/python3.6/site-packages/datatable/lib/__init__.py", line 31, in <module>
    from . import _datatable as core
ImportError: cannot import name '_datatable'
```

- How to reproduce the bug?
Create a venv on Ubuntu 18.04 and attempt to install datatable>0.9.0 into the venv.

- Your environment?
EC2 Instance of Ubuntu 18.04 + venv (Python 3.6)

**Comment by st-pasha** [comment]
We have an [installation guide](https://datatable.readthedocs.io/en/latest/start/install.html) that describes various ways to install, as well as possible troubleshooting steps.

I would recommend installing the latest version (0.11.0) of the package; and if that fails post the detailed description of what you did and what were the results.

**Comment by TravisCouture** [comment]
This fails with any version > 0.9.0 so 0.10.1 and 0.11.0. The error posted is from attempting to install with > 0.9.0.

**Comment by st-pasha** [comment]
Try to create a fresh venv, and then do `pip install datatable` -- what is the complete output of that command?

**Comment by glittershark** [comment]
Can confirm this is happening for me when attempting to package datatable for Nixpkgs. Appears to be caused by https://github.com/h2oai/datatable/commit/f32974eac86df4260d53844fe3037d0a3e32a55b

**Comment by st-pasha** [comment]
@glittershark Which version of datatable are you trying to package for Nixpkgs? The commit that you referred is over 2 years ago.
