### ISSUE TITLE
Does not work with python 3.6

### ISSUE THREAD

**Issue by Darel13712** [h2oai/datatable#2428]
# Description

Tried installing datatable with pyenv python 3.6.8 and 3.6.10

Installation takes extra long time and when I try to import it gives following error:
```
>>> import datatable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/darel/venv/lib/python3.6/site-packages/datatable/__init__.py", line 24, in <module>
    from .frame import Frame
  File "/home/darel/venv/lib/python3.6/site-packages/datatable/frame.py", line 23, in <module>
    from datatable.lib._datatable import Frame
  File "/home/darel/venv/lib/python3.6/site-packages/datatable/lib/__init__.py", line 31, in <module>
    from . import _datatable as core
ImportError: cannot import name '_datatable'
```

**But** if I install it into python 3.7.7 it works just fine.

# Steps to reproduce

```
pyenv install 3.6.10
.pyenv/versions/3.6.10/bin/python -m venv venv
source venv/bin/activate
pip install datatable
python
>>> import datatable
```
# Environment

- Ubuntu 18.04.4 LTS
- Python 3.6.8 and 3.6.10
```
blessed==1.17.5
colorama==0.4.3
datatable==0.10.1
six==1.14.0
typesentry==0.2.7
wcwidth==0.1.9
```

**Comment by st-pasha** [comment]
Given that "Installation takes extra long time", it means that your environment attempts to compile and install from source. We have released pre-built binary wheels for Linux x86-64 for pythons 3.5-3.8, I'd recommend looking through the verbose pip install logs in order to find out why they do not get picked up by your platform.

Alternatively, you may try to search where the `_datatable*.so` ended up, and manually move them to the correct location (which is the datatable/lib folder).

If all else fails, I recommend installing the latest dev version from github, see https://datatable.readthedocs.io/en/latest/install.html
