### ISSUE TITLE
compiling on ppc64le

### ISSUE THREAD

**Issue by ironv** [h2oai/datatable#1508]
I am trying to compile on a ppc64le box running Ubuntu 18.04.1 for python 3.6.5.  Installed LLVM6 and set export LLVM6=/usr/lib/llvm-6.0.

Here are the last few lines

    gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ic -Iinclude -I/root/anaconda3/include/python3.6m -c c/extras/murmurhash.cc -o build/temp.linux-ppc64le-3.6/c/extras/murmurhash.o -fopenmp -std=c++11 -Ic -fPIC -O3 -g0 -Wall -Wno-unused-value -Wno-unknown-pragmas -I/opt/anaconda3/include/python3.6m -isystem /opt/anaconda3/include/python3.6m -I/root/anaconda3/include -isystem /root/anaconda3/include -I/usr/lib/llvm-6.0/include -isystem /usr/lib/llvm-6.0/include -Ic
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ic -Iinclude -I/root/anaconda3/include/python3.6m -c c/extras/py_ftrl.cc -o build/temp.linux-ppc64le-3.6/c/extras/py_ftrl.o -fopenmp -std=c++11 -Ic -fPIC -O3 -g0 -Wall -Wno-unused-value -Wno-unknown-pragmas -I/opt/anaconda3/include/python3.6m -isystem /opt/anaconda3/include/python3.6m -I/root/anaconda3/include -isystem /root/anaconda3/include -I/usr/lib/llvm-6.0/include -isystem /usr/lib/llvm-6.0/include -Ic
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    c/extras/py_ftrl.cc: In static member function 'static void py::Ftrl::Type::init_methods_and_getsets(py::ExtType<py::Ftrl>::Methods&, py::ExtType<py::Ftrl>::GetSetters&)':
    c/extras/py_ftrl.cc:186:32: error: the value of 'py::fn___getstate__' is not usable in a constant expression
       mm.add<&Ftrl::m__getstate__, fn___getstate__>();
                                    ^~~~~~~~~~~~~~~
    c/extras/py_ftrl.cc:37:15: note: 'py::fn___getstate__' was not declared 'constexpr'
     static NoArgs fn___getstate__("__getstate__", nullptr);
                   ^~~~~~~~~~~~~~~
    c/extras/py_ftrl.cc:187:32: error: the value of 'py::fn___setstate__' is not usable in a constant expression
       mm.add<&Ftrl::m__setstate__, fn___setstate__>();
                                    ^~~~~~~~~~~~~~~
    c/extras/py_ftrl.cc:38:15: note: 'py::fn___setstate__' was not declared 'constexpr'
     static PKArgs fn___setstate__(1, 0, 0, false, false, {"state"},
                   ^~~~~~~~~~~~~~~
    error: command 'gcc' failed with exit status 1

I have the entire output of `make build` and can cut & paste that if it helps.  Any ideas?

**Comment by ironv** [comment]
I just installed `clang`.  I also set `export LD_LIBRARY_PATH=/usr/lib/llvm-6.0/lib:$LD_LIBRARY_PATH`.  I get an error much sooner now!

    python setup.py build
    
    Start setup.py
      command = `build`
    
    Find an LLVM installation
      Environment variable LLVM is not set
      Environment variable LLVM7 is not set
      Environment variable LLVM6 = /usr/lib/llvm-6.0
      Llvm directory: /usr/lib/llvm-6.0
      Version: llvm6
    
    Determine the compiler
      Environment variable `CXX` is not set
      Environment variable `CC` is not set
      Found Clang compiler /usr/lib/llvm-6.0/bin/clang++
    
    Prepare the environment
      CC = /usr/lib/llvm-6.0/bin/clang++
      CXX = /usr/lib/llvm-6.0/bin/clang++
      LDFLAGS = 
      ARCHFLAGS = -m64
      LLVM_CONFIG = 
      MACOSX_DEPLOYMENT_TARGET = 
    
    Find compile include directories
      `c` is the main C++ source directory
      `/opt/anaconda3/include/python3.6m` added from CONFINCLUDEPY
      `/root/anaconda3/include` added from sys.prefix
      `/usr/lib/llvm-6.0/include` added from Llvm package
      `/usr/lib/llvm-6.0/include/c++/v1` added from Llvm package
      Directory `/usr/lib/llvm-6.0/include/c++/v1` not found, ignoring
    
    Determine the extra compiler flags
      -fopenmp
      -std=c++11
      -stdlib=libc++
      -Ic
      -fPIC
      -O3
      -g0
      -Weverything
      -Wno-c++98-compat-pedantic
      -Wno-c99-extensions
      -Wno-exit-time-destructors
      -Wno-float-equal
      -Wno-global-constructors
      -Wno-switch-enum
      -Wno-weak-template-vtables
      -I/opt/anaconda3/include/python3.6m
      -isystem /opt/anaconda3/include/python3.6m
      -I/root/anaconda3/include
      -isystem /root/anaconda3/include
      -I/usr/lib/llvm-6.0/include
      -isystem /usr/lib/llvm-6.0/include
      -Ic
    
    Find the required dynamic libraries
      /usr/lib/llvm-6.0/lib/libomp.so does not exist
    
    Determine the extra linker flags
    
    Traceback (most recent call last):
      File "setup.py", line 122, in <module>
        extra_link_args = get_extra_link_args()
      File "/home/uname/datatable/ci/setup_utils.py", line 534, in get_extra_link_args
        for lib in find_linked_dynamic_libraries()))
      File "/home/uname/datatable/ci/setup_utils.py", line 599, in find_linked_dynamic_libraries
        stderr=subprocess.PIPE)
      File "/root/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/root/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'locate': 'locate'
    Makefile:63: recipe for target 'build' failed
    make: *** [build] Error 1

I see that `libomp.so` is in `/usr/lib/powerpc64le-linux-gnu`.   So I added that to LD_LIBRARY_PATH so that  `export LD_LIBRARY_PATH=/usr/lib/llvm-6.0/lib:/usr/lib/powerpc64le-linux-gnu:$LD_LIBRARY_PATH`.  I still get the same error and failure.

I have used R data.table for 4+ years now and can't wait to use this in python.  I appreciate your help.

**Comment by Nestak2** [comment]
@ironv I have the same issue as you. Could you walk me through for how to solve it, which of the above links to follow, what to install in my virtual environment? Sorry, I am a noobie and I don't understand "used the pre-built wheel and it worked".

**Comment by st-pasha** [comment]
@Nestak2 Try pip-installing one of the following wheel files, depending on your Python version:

- (Python 3.5) https://s3.amazonaws.com/artifacts.h2o.ai/releases/ai/h2o/pydatatable/0.9.0/ppc64le-centos7/datatable-0.9.0-cp35-cp35m-linux_ppc64le.whl
- (Python 3.6) https://s3.amazonaws.com/artifacts.h2o.ai/releases/ai/h2o/pydatatable/0.9.0/ppc64le-centos7/datatable-0.9.0-cp36-cp36m-linux_ppc64le.whl
- (Python 3.7) https://s3.amazonaws.com/artifacts.h2o.ai/releases/ai/h2o/pydatatable/0.9.0/ppc64le-centos7/datatable-0.9.0-cp37-cp37m-linux_ppc64le.whl

**Comment by Nestak2** [comment]
@st-pasha Thanks! Is there also a wheel for Mac, I am using this OS?

**Comment by st-pasha** [comment]
For Mac you can just install from pip: `pip install datatable`.

**Comment by Nestak2** [comment]
@st-pasha Unfortunately, `pip install datatable` this results in the error message reported above by @ironv : 
```
ERROR: Complete output from command /Users/nnov/anaconda3/envs/py37_3d/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/vr/0fs4kj9968q6pwg4072hb6780000gq/T/pip-install-xz9cyolv/datatable/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/vr/0fs4kj9968q6pwg4072hb6780000gq/T/pip-wheel-mu75uy1x --python-tag cp37:
  ERROR:
  Start setup.py
    command = `bdist_wheel`

  Find an LLVM installation
    Environment variable LLVM is not set
    Environment variable LLVM7 is not set
    ...
    ...
```

Thanks for supporting and answering my questions so far! Is there anything else I could try to fix this and install datatable on my Mac?

**Comment by st-pasha** [comment]
@Nestak2  Please try again

**Comment by Nestak2** [comment]
@st-pasha Thanks a lot, yes, now it got installed and it works in my jlab!
